/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace TaskEscrow {
      
    export type TaskStruct = {creator: AddressLike, worker: AddressLike, bounty: BigNumberish, funded: boolean, completed: boolean}

    export type TaskStructOutput = [creator: string, worker: string, bounty: bigint, funded: boolean, completed: boolean] & {creator: string, worker: string, bounty: bigint, funded: boolean, completed: boolean }
  
    }

  export interface TaskEscrowInterface extends Interface {
    getFunction(nameOrSignature: "createTask" | "fundTask" | "getTask" | "owner" | "refundTask" | "releasePayment" | "tasks" | "usdc"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "PaymentReleased" | "TaskCreated" | "TaskFunded" | "TaskRefunded"): EventFragment;

    encodeFunctionData(functionFragment: 'createTask', values: [BigNumberish, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'fundTask', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getTask', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'refundTask', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'releasePayment', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'tasks', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'usdc', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'createTask', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fundTask', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTask', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'refundTask', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'releasePayment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tasks', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdc', data: BytesLike): Result;
  }

  
    export namespace PaymentReleasedEvent {
      export type InputTuple = [taskId: BigNumberish, worker: AddressLike, amount: BigNumberish];
      export type OutputTuple = [taskId: bigint, worker: string, amount: bigint];
      export interface OutputObject {taskId: bigint, worker: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TaskCreatedEvent {
      export type InputTuple = [taskId: BigNumberish, creator: AddressLike, worker: AddressLike, bounty: BigNumberish];
      export type OutputTuple = [taskId: bigint, creator: string, worker: string, bounty: bigint];
      export interface OutputObject {taskId: bigint, creator: string, worker: string, bounty: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TaskFundedEvent {
      export type InputTuple = [taskId: BigNumberish, creator: AddressLike, amount: BigNumberish];
      export type OutputTuple = [taskId: bigint, creator: string, amount: bigint];
      export interface OutputObject {taskId: bigint, creator: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TaskRefundedEvent {
      export type InputTuple = [taskId: BigNumberish, creator: AddressLike, amount: BigNumberish];
      export type OutputTuple = [taskId: bigint, creator: string, amount: bigint];
      export interface OutputObject {taskId: bigint, creator: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface TaskEscrow extends BaseContract {
    
    connect(runner?: ContractRunner | null): TaskEscrow;
    waitForDeployment(): Promise<this>;

    interface: TaskEscrowInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    createTask: TypedContractMethod<
      [taskId: BigNumberish, worker: AddressLike, bounty: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    fundTask: TypedContractMethod<
      [taskId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getTask: TypedContractMethod<
      [taskId: BigNumberish, ],
      [TaskEscrow.TaskStructOutput],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    refundTask: TypedContractMethod<
      [taskId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    releasePayment: TypedContractMethod<
      [taskId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    tasks: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, boolean, boolean] & {creator: string, worker: string, bounty: bigint, funded: boolean, completed: boolean }],
      'view'
    >
    

    
    usdc: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'createTask'): TypedContractMethod<
      [taskId: BigNumberish, worker: AddressLike, bounty: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'fundTask'): TypedContractMethod<
      [taskId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getTask'): TypedContractMethod<
      [taskId: BigNumberish, ],
      [TaskEscrow.TaskStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'refundTask'): TypedContractMethod<
      [taskId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'releasePayment'): TypedContractMethod<
      [taskId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'tasks'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, boolean, boolean] & {creator: string, worker: string, bounty: bigint, funded: boolean, completed: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'usdc'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'PaymentReleased'): TypedContractEvent<PaymentReleasedEvent.InputTuple, PaymentReleasedEvent.OutputTuple, PaymentReleasedEvent.OutputObject>;
getEvent(key: 'TaskCreated'): TypedContractEvent<TaskCreatedEvent.InputTuple, TaskCreatedEvent.OutputTuple, TaskCreatedEvent.OutputObject>;
getEvent(key: 'TaskFunded'): TypedContractEvent<TaskFundedEvent.InputTuple, TaskFundedEvent.OutputTuple, TaskFundedEvent.OutputObject>;
getEvent(key: 'TaskRefunded'): TypedContractEvent<TaskRefundedEvent.InputTuple, TaskRefundedEvent.OutputTuple, TaskRefundedEvent.OutputObject>;

    filters: {
      
      'PaymentReleased(uint256,address,uint256)': TypedContractEvent<PaymentReleasedEvent.InputTuple, PaymentReleasedEvent.OutputTuple, PaymentReleasedEvent.OutputObject>;
      PaymentReleased: TypedContractEvent<PaymentReleasedEvent.InputTuple, PaymentReleasedEvent.OutputTuple, PaymentReleasedEvent.OutputObject>;
    

      'TaskCreated(uint256,address,address,uint256)': TypedContractEvent<TaskCreatedEvent.InputTuple, TaskCreatedEvent.OutputTuple, TaskCreatedEvent.OutputObject>;
      TaskCreated: TypedContractEvent<TaskCreatedEvent.InputTuple, TaskCreatedEvent.OutputTuple, TaskCreatedEvent.OutputObject>;
    

      'TaskFunded(uint256,address,uint256)': TypedContractEvent<TaskFundedEvent.InputTuple, TaskFundedEvent.OutputTuple, TaskFundedEvent.OutputObject>;
      TaskFunded: TypedContractEvent<TaskFundedEvent.InputTuple, TaskFundedEvent.OutputTuple, TaskFundedEvent.OutputObject>;
    

      'TaskRefunded(uint256,address,uint256)': TypedContractEvent<TaskRefundedEvent.InputTuple, TaskRefundedEvent.OutputTuple, TaskRefundedEvent.OutputObject>;
      TaskRefunded: TypedContractEvent<TaskRefundedEvent.InputTuple, TaskRefundedEvent.OutputTuple, TaskRefundedEvent.OutputObject>;
    
    };
  }